#!/bin/sh

# Copyright (c) 2016-2017 Jorge Giner Cordero
# 
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
# 
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# This script takes all files inside data/, optimizes some of them, and
# generates a data.pak inside datapak/ with all files zipped without
# compression.
# It needs ImageMagick, bc and zip installed.
# It needs to create a temporary folder datapak.tmp/ .

make_data () {
	for fd in "$datad"/*.bmp; do
		f=`basename $fd`
		origsize=$(stat -c%s $fd)
		ncolors=$(identify -format %k $fd)
		convert $fd -colors $ncolors BMP3:"$buildd"/$f
		newsize=$(stat -c%s "$buildd"/$f)
		percent=`echo "$newsize*100/$origsize" | bc`
		if [ $newsize -lt $origsize ]; then
			echo "File $f (ncolors $ncolors) will be $percent% of original"
		else
			cp $fd "$buildd"
		fi
	done
	cp "$datad"/tileset.bmp "$buildd"
	cp "$datad"/stargate.bmp "$buildd"
	cp "$datad"/*.txt "$buildd"
	cp "$datad"/*.xm "$buildd"
	cp "$datad"/*.wav "$buildd"
}

confirm () {
	while true; do
		read -p "${1:-Continue?} [y/n]: " yn
		case $yn in
			[Yy]* ) return 0 ; break ;;
			[Nn]* ) return 1 ; break ;;
		*) echo "Please answer yes or no." ;;
		esac
	done
}

srcd=`dirname "$0"`
datad="$srcd/data"
datapakd="$srcd/datapak"
buildd=data.build
if [ -d "$buildd" ]; then
	echo '****** WARNING! ******'
	echo We need a temporary folder named $buildd here,
	echo but it already exists.
	confirm "Folder $buildd will be removed now, continue?" || exit 0
	rm -r "$buildd"
fi
mkdir -p "$buildd"
make_data
zip -FS -j -Zstore "$datapakd"/data.pak "$buildd"/*
rm -r "$buildd"
